using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Collections.Generic;
using System.Windows.Forms;

namespace MabiRemote {
public class EditDialog : Form {
    UiScaleState displayScale;
    protected override void OnLoad(EventArgs e){base.OnLoad(e);displayScale=new UiScaleState(this);displayScale.Apply(UiSizing.Percent);}
    protected override void OnFormClosed(FormClosedEventArgs e){base.OnFormClosed(e);if(displayScale!=null)displayScale.Dispose();}
    public FlowLayoutPanel Content; public Button OK;
    public EditDialog(string title){Text=title;Width=580;Height=540;MinimumSize=new Size(520,420);StartPosition=FormStartPosition.CenterParent;Font=new Font("맑은 고딕",9.5F);BackColor=Color.FromArgb(243,247,247);Content=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(16)};Controls.Add(Content);var buttons=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=52,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(8)};OK=new Button{Text="저장",DialogResult=DialogResult.OK,Width=95,Height=32,BackColor=Color.FromArgb(15,109,101),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};OK.FlatAppearance.BorderColor=Color.FromArgb(15,109,101);var cancel=new Button{Text="취소",DialogResult=DialogResult.Cancel,Width=95,Height=32,BackColor=Color.White,FlatStyle=FlatStyle.Flat};cancel.FlatAppearance.BorderColor=Color.FromArgb(200,215,215);buttons.Controls.Add(OK);buttons.Controls.Add(cancel);Controls.Add(buttons);AcceptButton=OK;CancelButton=cancel;}
    public void Add(string label,Control c){Content.Controls.Add(new Label{Text=label,AutoSize=true,Margin=new Padding(0,8,0,3),Font=new Font("맑은 고딕",9.5F,FontStyle.Bold)});Content.Controls.Add(c);}
    public void Hint(string s){Content.Controls.Add(new Label{Text=s,Width=500,AutoSize=true,MaximumSize=new Size(500,0),ForeColor=Color.DimGray,Margin=new Padding(0,8,0,4)});}
}
public partial class MainForm {
    Dictionary<string,Image> iconCache=new Dictionary<string,Image>();
    List<string> ItemNames(){return snap.Items.Select(x=>J.S(x,"DisplayName")).Concat(snap.Gatherables.Select(x=>J.S(x,"DisplayName"))).Concat(snap.Recipes.Select(x=>Planner.Product(J.S(x,"DisplayName")))).Concat(cfg.Stocks.Select(x=>x.Name)).Where(x=>x!="").Distinct().OrderBy(x=>x).ToList();}
    void Fill(ComboBox box,IEnumerable<string> values,string selected){box.BeginUpdate();box.Items.Clear();box.Items.AddRange(values.Cast<object>().ToArray());if(selected!=null&&box.Items.Contains(selected))box.SelectedItem=selected;else if(box.Items.Count>0)box.SelectedIndex=0;box.EndUpdate();}
    void MoveGoal(int delta){if(!CanEdit())return;var g=Selected<Goal>(goalGrid);if(g==null)return;int i=cfg.Goals.IndexOf(g),n=i+delta;if(n<0||n>=cfg.Goals.Count)return;cfg.Goals.RemoveAt(i);cfg.Goals.Insert(n,g);Save();RenderGoals();foreach(DataGridViewRow row in goalGrid.Rows)if(row.Tag==g)row.Selected=true;}
    void EditStock(string name){
        if(!CanEdit())return;var names=ItemNames();if(names.Count==0){Notice("아이템 목록을 불러오지 못했습니다. 게임 연결 상태를 확인하세요.");return;}var old=cfg.Stocks.FirstOrDefault(x=>x.Name==name);
        using(var d=new EditDialog("재고 목표 · 자동 채집")){d.Height=350;var combo=Combo(460);Fill(combo,names,name);var n=Number(old==null?100:old.Target,1000000);var gather=new CheckBox{Text="목표 미달 시 자동 채집",AutoSize=true,Checked=old==null||old.Gather,Margin=new Padding(0,6,0,6)};d.Add("아이템",combo);d.Add("목표 수량",n);d.Content.Controls.Add(gather);d.Hint("목표 수량에 도달할 때까지 부족한 수량을 자동으로 채집합니다.");if(d.ShowDialog(this)!=DialogResult.OK)return;string selected=Convert.ToString(combo.SelectedItem);var g=cfg.Stocks.FirstOrDefault(x=>x.Name==selected)??new StockGoal{Name=selected};g.Target=(int)n.Value;g.Gather=gather.Checked;if(!cfg.Stocks.Contains(g))cfg.Stocks.Add(g);Save();RenderItems();}
    }
    void AssignIcon(){string name=Selected<string>(itemGrid);if(name==null)return;using(var d=new OpenFileDialog{Filter="아이콘 이미지|*.png;*.jpg;*.jpeg;*.bmp"}){if(d.ShowDialog(this)!=DialogResult.OK)return;try{Directory.CreateDirectory(Path.Combine(Storage.Root,"icons"));string p=Path.Combine(Storage.Root,"icons",Guid.NewGuid().ToString("N")+".png");using(var im=Image.FromFile(d.FileName))using(var small=new Bitmap(im,new Size(40,40)))small.Save(p,System.Drawing.Imaging.ImageFormat.Png);cfg.Icons[name]=p;Save();RenderItems();}catch(Exception ex){Notice("이미지 등록 실패: "+UserError(ex));}}}
    Image IconFor(string name){string file;if(!cfg.Icons.TryGetValue(name,out file)||!File.Exists(file))return null;Image im;if(iconCache.TryGetValue(file,out im))return im;try{using(var src=Image.FromFile(file))im=new Bitmap(src,new Size(28,28));iconCache[file]=im;return im;}catch{return null;}}
    void RenderAll(){RenderManualInfo();RenderFacilities();RenderGoals();RenderRecipes();RenderItems();RenderManual();UpdateLiveLabels();}
    string Duration(double seconds){if(seconds<=0)return "완료 대기";var t=TimeSpan.FromSeconds(seconds);return t.TotalHours>=1?((int)t.TotalHours)+"시간 "+t.Minutes+"분":t.Minutes+"분 "+t.Seconds+"초";}
    string Reason(object r){if(r==null)return "가공법 없음";if(J.B(r,"Alterable"))return "등록 가능";string reason=J.S(r,"Reason");var missing=J.Rows(J.Get(r,"MissingIngredients"));if(missing.Count>0)return String.Join(", ",missing.Select(x=>J.S(x,"DisplayName")+" "+J.N(x,"Owned")+"/"+J.N(x,"Required")));switch(reason){case "insufficient_facility_level":return "시설 레벨 부족";case "ingredient_locked":return "재료 잠금";case "insufficient_transfer_cost":return "이동 비용 부족";case "not_enough_ingredient":return "재료 부족";default:return reason==""?"등록 불가":FriendlyText.Code(reason);}}
    void RenderItems(){if(itemGrid==null)return;string selected=Selected<string>(itemGrid);int first=itemGrid.FirstDisplayedScrollingRowIndex;itemGrid.Rows.Clear();var names=snap.Items.GroupBy(x=>J.S(x,"DisplayName")).OrderBy(x=>x.Key);foreach(var g in names){int bag=(int)g.Where(x=>J.S(x,"Location")=="inventory").Sum(x=>J.N(x,"Count"));if(itemLocation.SelectedIndex==0&&bag==0)continue;if(!String.IsNullOrWhiteSpace(itemSearch.Text)&&g.Key.IndexOf(itemSearch.Text,StringComparison.CurrentCultureIgnoreCase)<0)continue;var goal=cfg.Stocks.FirstOrDefault(x=>x.Name==g.Key);int i=itemGrid.Rows.Add(g.Key,bag,g.Where(x=>J.S(x,"Location")=="account_storage").Sum(x=>J.N(x,"Count")),g.Where(x=>J.S(x,"Location")=="character_storage").Sum(x=>J.N(x,"Count")),J.S(g.First(),"CategoryDisplayName"),goal==null?"—":goal.Target.ToString(),goal!=null&&goal.Gather?"ON":"OFF",IconFor(g.Key));itemGrid.Rows[i].Tag=g.Key;if(g.Key==selected)itemGrid.Rows[i].Selected=true;}if(first>=0&&first<itemGrid.Rows.Count)itemGrid.FirstDisplayedScrollingRowIndex=first;stockGrid.Rows.Clear();foreach(var g in cfg.Stocks){int i=stockGrid.Rows.Add(g.Name,g.Target,g.Gather?"ON":"OFF");stockGrid.Rows[i].Tag=g;}}
    void UpdateLiveLabels(){if(closing||IsDisposed)return;if(activityDiagnosticPath!=""&&DateTime.UtcNow-activityDiagnosticStarted>=TimeSpan.FromMinutes(30))EndActivityDiagnostic("30분 기록 완료");if(placeLabel==null)return;DeliverPendingNotices();connectionLabel.Text=(demo?"DEMO · ":"")+(connected?"게임 연결됨":connectionIssue);connectionLabel.ForeColor=connected?Accent:Color.Firebrick;placeLabel.Text=snap.At==DateTime.MinValue?"—":J.S(snap.Environment,"GameSpaceDisplayName")+"  "+FriendlyText.Weather(J.S(snap.Environment,"Weather"));activityLabel.Text=actionOwned?actionText:ActivityText();weightLabel.Text=snap.At==DateTime.MinValue?"—":snap.Weight.ToString("0.#")+" / "+snap.Capacity.ToString("0.#")+"  ("+(snap.Capacity>0?snap.Weight/snap.Capacity*100:0).ToString("0")+"%)";wingsLabel.Text=snap.At==DateTime.MinValue?"—":snap.Count("정령의 날개",false).ToString("N0")+"개";weightLabel.ForeColor=snap.Full(cfg.FullPercent)?Color.Firebrick:Ink;startButton.Text=auto?"자동화 중지":startRequested?"시작 취소":"자동화 시작";startButton.Enabled=!stopping&&(auto||(!actionOwned&&(!busy||polling)&&!MusicActive));fishCombo.Enabled=!auto&&!busy&&!ownsFishing;refreshLabel.Text=snap.At==DateTime.MinValue?"":((int)(DateTime.UtcNow-snap.At).TotalSeconds)+"초 전 조회";if(snap.At!=DateTime.MinValue)RenderFacilities();UpdateMusicStatus();}
    string ActivityText(){if(!connected)return "연결 대기";if(J.B(J.Get(snap.Activity,"Performance"),"IsPlaying"))return "연주 중 · "+J.S(J.Get(snap.Activity,"Performance"),"MusicTitle");if(ActivityCompletionWatch.RewardReady(snap))return "사냥터 보상 수령 대기";if(snap.Fishing)return ownsFishing?"자동 낚시 중":"낚시 중";if(snap.Dungeon!="NotInDungeon")return "던전 · "+FriendlyText.Dungeon(snap.Dungeon);if(J.B(snap.Section("combatState"),"IsInCombat"))return "전투 중";if(J.B(snap.Section("autoTravel"),"IsAutoTraveling"))return "이동 중";if(J.B(snap.Section("autoPlay"),"IsAutoPlaying"))return "자동 진행 중";return snap.Busy(false)?"다른 행동 중":"대기";}
}
}
