using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MabiRemote {
public partial class MainForm : Form {
    readonly bool demo, preview; Settings cfg; IBridge bridge; Snapshot snap=new Snapshot();
    bool connected, busy, auto, fishEnabled, ownsFishing, actionOwned, stopRequested, closing, hasCatalog;
    string connectionIssue="연결 확인 중";
    DateTime lastUiAt=DateTime.MinValue;
    int generation; string actionText="대기", watched=""; DateTime nextPoll=DateTime.MinValue, catalogAt=DateTime.MinValue;
    Dictionary<string,object> commands=new Dictionary<string,object>();
    Dictionary<string,DateTime> cooldown=new Dictionary<string,DateTime>();
    List<Goal> manualQueue=new List<Goal>();
    Label connectionLabel, placeLabel, activityLabel, weightLabel, wingsLabel, refreshLabel, planLabel, cliLabel;
    Button startButton, pauseButton, stopButton; CheckBox fishCheck, storageCheck;
    NumericUpDown fullNumber; ComboBox fishCombo;
    TabControl tabs=new TabControl(); DataGridView facilityGrid,goalGrid,recipeGrid,manualGrid,itemGrid,stockGrid,landmarkGrid;
    Label activityWatchLabel, lastNotificationLabel;
    TextBox logBox, itemSearch; ComboBox itemLocation; NotifyIcon tray; Timer timer=new Timer();
    static readonly Color Ink=Color.FromArgb(28,45,50), Accent=Color.FromArgb(15,109,101), Canvas=Color.FromArgb(243,247,247);
    public MainForm(bool demoMode,bool previewMode){
        demo=demoMode;preview=previewMode;cfg=demo?new Settings():Storage.Load();
        if(demo){cfg.Playlist.Add(new PlaylistEntry{Title="악보: 첫 곡",Instrument="하프"});cfg.Playlist.Add(new PlaylistEntry{Title="악보: 두 번째 곡",Instrument="피아노"});cfg.Goals.Add(new Goal{Name="목재",Product="목재",Target=100});cfg.Goals.Add(new Goal{Name="옷감",Product="옷감",Mode="unlimited"});cfg.Stocks.Add(new StockGoal{Name="통나무",Target=300});cfg.FishName="연어";}
        bridge=demo?(IBridge)new DemoBridge():(IBridge)new GameBridge(cfg.CliPath);
        if(demo){var db=(DemoBridge)bridge;db.Works.Add(J.Obj("DisplayName","목재","FacilityName","목재 가공 시설","State","Completed","IsCompleted",true,"RemainingSeconds",0));db.Works.Add(J.Obj("DisplayName","목재","FacilityName","목재 가공 시설","State","InProgress","IsCompleted",false,"RemainingSeconds",750));db.Works.Add(J.Obj("DisplayName","옷감","FacilityName","옷감 가공 시설","State","InProgress","IsCompleted",false,"RemainingSeconds",1800));}
        Text="에린 리모컨 "+Updates.CurrentVersion+(demo?" · 데모":""); Width=1220;Height=840;MinimumSize=new Size(1020,720);StartPosition=FormStartPosition.CenterScreen;
        Font=new Font("맑은 고딕",9F);BackColor=Canvas;ForeColor=Ink;AutoScaleMode=AutoScaleMode.Dpi;
        BuildUI(); LoadEmbeddedCatalog();
        tray=new NotifyIcon{Icon=SystemIcons.Information,Text="에린 리모컨",Visible=!preview};
        tray.DoubleClick+=(s,e)=>{Show();WindowState=FormWindowState.Normal;Activate();};
        timer.Interval=250;timer.Tick+=async(s,e)=>{if((DateTime.UtcNow-lastUiAt).TotalSeconds>=1){UpdateLiveLabels();lastUiAt=DateTime.UtcNow;}if(!busy&&!closing&&DateTime.UtcNow>=nextPoll)await Poll();};
        Shown+=async(s,e)=>{if(!preview){await Poll();timer.Start();}if(Storage.LastLoadWarning!="")Log(Storage.LastLoadWarning);};
        Load+=(s,e)=>ApplyDisplayScale(cfg.UiScale);FormClosed+=(s,e)=>{if(displayScale!=null)displayScale.Dispose();};
        FormClosing+=OnClosing;
    }
    Label Label(string text,int size){return new Label{Text=text,AutoSize=true,Font=new Font("맑은 고딕",size,size>=15?FontStyle.Bold:FontStyle.Regular),ForeColor=Ink,Margin=new Padding(8)};}
    Button Button(string text,Action click,bool accent=false){var b=new Button{Text=text,AutoSize=true,Height=36,MinimumSize=new Size(100,34),FlatStyle=FlatStyle.Flat,BackColor=accent?Accent:Color.White,ForeColor=accent?Color.White:Ink,Margin=new Padding(4),Padding=new Padding(7,2,7,2)};b.FlatAppearance.BorderColor=Color.FromArgb(200,215,215);b.Click+=(s,e)=>click();return b;}
    FlowLayoutPanel Bar(){return new FlowLayoutPanel{Dock=DockStyle.Top,AutoSize=true,WrapContents=true,Padding=new Padding(5)};}
    ComboBox Combo(int width){return new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=width,IntegralHeight=false,DropDownHeight=360,Margin=new Padding(6,8,6,6)};}
    NumericUpDown Number(decimal val,int max){return new NumericUpDown{Value=val,Maximum=max,Minimum=0,Width=100,ThousandsSeparator=true,Margin=new Padding(6,8,6,6)};}
    DataGridView Grid(params string[] cols){var g=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,EnableHeadersVisualStyles=false,AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.DisplayedCells};g.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(228,237,236);g.ColumnHeadersDefaultCellStyle.ForeColor=Ink;g.ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.AutoSize;g.ColumnHeadersDefaultCellStyle.WrapMode=DataGridViewTriState.True;g.DefaultCellStyle.WrapMode=DataGridViewTriState.True;g.DefaultCellStyle.Padding=new Padding(4,5,4,5);g.RowTemplate.Height=34;g.DefaultCellStyle.SelectionBackColor=Color.FromArgb(215,237,231);g.DefaultCellStyle.SelectionForeColor=Ink;g.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(248,250,250);foreach(var c in cols){int index=g.Columns.Add(c,c);g.Columns[index].MinimumWidth=65;}return g;}
    TabPage Page(string title,string hint,Control content,FlowLayoutPanel bar){var p=new TabPage(title){BackColor=Canvas,Padding=new Padding(12)};p.Controls.Add(content);if(bar!=null)p.Controls.Add(bar);var l=new Label{Text=hint,Dock=DockStyle.Top,AutoSize=true,MaximumSize=new Size(1000,0),Padding=new Padding(4,6,4,8),ForeColor=Color.FromArgb(76,99,100)};p.Controls.Add(l);p.Resize+=(s,e)=>l.MaximumSize=new Size(Math.Max(100,p.ClientSize.Width-24),0);tabs.TabPages.Add(p);return p;}
    void BuildUI(){
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=5,Padding=new Padding(16)};
        root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.Absolute,90));root.RowStyles.Add(new RowStyle(SizeType.Absolute,58));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));Controls.Add(root);
        var heading=Bar();heading.Dock=DockStyle.Top;heading.AutoSizeMode=AutoSizeMode.GrowAndShrink;heading.Controls.Add(Label("에린 리모컨",20));connectionLabel=Label(demo?"DEMO · 게임 조작 없음":"연결 확인 중",10);heading.Controls.Add(connectionLabel);root.Controls.Add(heading,0,0);
        var cards=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1};for(int i=0;i<4;i++)cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25F));
        placeLabel=Card(cards,0,"현재 위치","—");activityLabel=Card(cards,1,"현재 행동","—");weightLabel=Card(cards,2,"가방 무게","—");wingsLabel=Card(cards,3,"정령의 날개","—");root.Controls.Add(cards,0,1);
        var controls=Bar();controls.Dock=DockStyle.Fill;
        startButton=Button("자동화 시작",StartAutomation,true);pauseButton=Button("예약 일시정지",async()=>await PauseUser());stopButton=Button("중지",async()=>await StopOwned());
        controls.Controls.Add(startButton);controls.Controls.Add(pauseButton);controls.Controls.Add(stopButton);controls.Controls.Add(Button("새로고침",async()=>{if(!busy)await Poll(true);}));root.Controls.Add(controls,0,2);
        tabs.Multiline=true;tabs.Dock=DockStyle.Fill;tabs.Font=new Font("맑은 고딕",10);root.Controls.Add(tabs,0,3);
        var footer=Bar();footer.Dock=DockStyle.Top;planLabel=Label("자동화 OFF · 버튼을 눌러야 게임 작업을 실행합니다.",9);refreshLabel=Label("",9);footer.Controls.Add(planLabel);footer.Controls.Add(refreshLabel);root.Controls.Add(footer,0,4);
        BuildFacilities();BuildGoals();BuildManual();BuildInventory();BuildFishing();BuildLandmarks();BuildSettings();BuildUpdates();BuildRoutes();BuildJukebox();
    }
    Label Card(TableLayoutPanel host,int col,string title,string value){var p=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Margin=new Padding(4)};var top=new Label{Text=title,AutoSize=true,Location=new Point(10,8),ForeColor=Color.FromArgb(83,111,112)};var val=new Label{Text=value,Location=new Point(10,34),Size=new Size(340,34),Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right,Font=new Font("맑은 고딕",12,FontStyle.Bold),TextAlign=ContentAlignment.TopLeft};p.Controls.Add(top);p.Controls.Add(val);host.Controls.Add(p,col,0);return val;}
    void BuildFacilities(){
        facilityGrid=Grid("시설","전체 슬롯","빈 슬롯","완료","진행·대기","다음 완료까지","마지막 완료까지","가공 품목");
        float[] widths={171,83,81,69,102,104,99,422};for(int i=0;i<widths.Length;i++){facilityGrid.Columns[i].FillWeight=widths[i];facilityGrid.Columns[i].SortMode=DataGridViewColumnSortMode.NotSortable;}facilityGrid.Columns[5].HeaderText="다음 완료\n남은 시간";facilityGrid.Columns[6].HeaderText="최종 완료\n남은 시간";
        var bar=Bar();bar.Controls.Add(Button("선택 시설 자동 가공",()=>{var n=Selected<string>(facilityGrid);if(n!=null){autoFacilityCombo.SelectedItem=n;tabs.SelectedIndex=1;}}));bar.Controls.Add(Button("선택 시설 수동 가공",()=>{var n=Selected<string>(facilityGrid);if(n!=null){manualFacilityCombo.SelectedItem=n;tabs.SelectedIndex=2;}}));bar.Controls.Add(Button("일괄 수령",async()=>await ManualCollect()));
        Page("가공 시설","전체 슬롯은 설정 · 기록 탭에서 시설별로 변경합니다 (기본 7칸). 완료 후 미수령 작업도 슬롯을 차지합니다. 모든 시설을 항상 표시합니다.",facilityGrid,bar);RenderFacilities();
    }
    void BuildGoals(){
        goalGrid=Grid("사용","가공법 / 완제품","방식","목표","진행 / 보유","예약 작업","상태");var bar=Bar();autoFacilityCombo=Combo(180);Fill(autoFacilityCombo,Facilities.Names,null);autoFacilityCombo.SelectedIndexChanged+=(s,e)=>RenderGoals();bar.Controls.Add(autoFacilityCombo);
        bar.Controls.Add(Button("목표 추가",()=>EditGoal(null)));bar.Controls.Add(Button("선택 수정",()=>EditGoal(Selected<Goal>(goalGrid))));bar.Controls.Add(Button("선택 삭제",()=>{if(CanEdit()){var g=Selected<Goal>(goalGrid);if(g!=null){cfg.Goals.Remove(g);Save();RenderGoals();}}}));bar.Controls.Add(Button("횟수 초기화",()=>{if(CanEdit()){var g=Selected<Goal>(goalGrid);if(g!=null){g.RunsDone=0;Save();RenderGoals();}}}));bar.Controls.Add(Button("우선순위 ↑",()=>MoveGoal(-1)));bar.Controls.Add(Button("우선순위 ↓",()=>MoveGoal(1)));
        Page("자동 가공","시설 선택 → 반복 목표 설정. 등록 횟수·목표 보유 수량·무제한을 지원하며 시설의 빈 슬롯만 사용합니다. 시설 슬롯 수만큼 재료를 묶음 준비합니다. 배합표가 없는 가공법은 등록하지 않습니다.",goalGrid,bar);
    }
    void BuildManual(){
        recipeGrid=Grid("가공법","지금 등록 가능","1회 생산","부족 재료 / 사유");manualGrid=Grid("시설","가공법","1회성 등록 수");
        var split=new SplitContainer{Dock=DockStyle.Fill,Orientation=Orientation.Horizontal,SplitterDistance=220};split.Panel1.Controls.Add(recipeGrid);split.Panel2.Controls.Add(manualGrid);var bar=Bar();
        manualFacilityCombo=Combo(180);Fill(manualFacilityCombo,Facilities.Names,null);manualInfoLabel=Label("",9);manualFacilityCombo.SelectedIndexChanged+=(s,e)=>{RenderRecipes();RenderManualInfo();};manualShowAll=new CheckBox{Text="전체 가공법",AutoSize=true,Margin=new Padding(6,10,6,6)};manualShowAll.CheckedChanged+=(s,e)=>RenderRecipes();bar.Controls.Add(manualFacilityCombo);bar.Controls.Add(manualShowAll);bar.Controls.Add(manualInfoLabel);
        bar.Controls.Add(Button("선택 품목 예약",()=>AddManual()));bar.Controls.Add(Button("예약 제거",()=>{if(CanEdit()){var g=Selected<Goal>(manualGrid);if(g!=null)manualQueue.Remove(g);RenderManual();}}));bar.Controls.Add(Button("수령 후 일괄 등록",async()=>await ManualRegister(),true));bar.Controls.Add(Button("일괄 수령",async()=>await ManualCollect()));
        Page("수동 가공","시설 선택 → 품목과 등록 수 예약 → 수령 후 일괄 등록. 완료 작업은 예약 슬롯에서 제외하며, 자동 수령 후 실제 빈 슬롯에 한 번 등록합니다. 가공법 분류가 다르면 전체 목록에서 선택하세요.",split,bar);
    }
    void BuildInventory(){itemGrid=Grid("아이템","가방","계정 창고","캐릭터 창고","분류","목표","자동 채집");var iconColumn=new DataGridViewImageColumn{Name="아이콘",HeaderText="",ImageLayout=DataGridViewImageCellLayout.Zoom,FillWeight=40};iconColumn.DefaultCellStyle.NullValue=null;itemGrid.Columns.Add(iconColumn);stockGrid=Grid("아이템","목표","자동 채집");itemGrid.SelectionChanged+=(s,e)=>{};var split=new SplitContainer{Dock=DockStyle.Fill,Orientation=Orientation.Horizontal,SplitterDistance=245};split.Panel1.Controls.Add(itemGrid);split.Panel2.Controls.Add(stockGrid);var bar=Bar();itemSearch=new TextBox{AccessibleName="아이템 이름 검색",Width=130,Margin=new Padding(4,8,4,4)};itemSearch.TextChanged+=(s,e)=>RenderItems();itemLocation=Combo(110);itemLocation.Items.AddRange(new object[]{"가방 보유","전체 보유"});itemLocation.SelectedIndex=0;itemLocation.SelectedIndexChanged+=(s,e)=>RenderItems();bar.Controls.Add(itemLocation);bar.Controls.Add(itemSearch);bar.Controls.Add(Button("선택 재고 목표",()=>EditStock(Selected<string>(itemGrid))));bar.Controls.Add(Button("재고 목표 추가",()=>EditStock(null)));bar.Controls.Add(Button("목표 수정",()=>{var g=Selected<StockGoal>(stockGrid);if(g!=null)EditStock(g.Name);}));bar.Controls.Add(Button("목표 삭제",()=>{if(CanEdit()){var g=Selected<StockGoal>(stockGrid);if(g!=null)cfg.Stocks.Remove(g);Save();RenderItems();}}));bar.Controls.Add(Button("아이콘 지정",()=>AssignIcon()));inventoryGatherStatus=Label(gatherStatus,9);inventoryGatherStatus.MaximumSize=new Size(900,0);bar.Controls.Add(inventoryGatherStatus);Page("재고 · 채집","목표 미달 품목은 빈 시간에 채집합니다. CLI는 1회 최대 100개 단위여서 초과 수집할 수 있습니다. 자동 판매·분해·창고 이동은 지원되지 않습니다.",split,bar);}
    void BuildFishing(){var p=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};p.Controls.Add(Label("다른 예약이 없을 때 자동 낚시",16));p.Controls.Add(Label("낚시 어종 선택",10));fishCombo=Combo(360);p.Controls.Add(fishCombo);fishCheck=new CheckBox{Text="빈 시간 자동 낚시 ON",AutoSize=true,Margin=new Padding(8,12,8,8)};fishCheck.CheckedChanged+=async(s,e)=>{if(fishCheck.Checked&&fishCombo.SelectedItem==null){fishCheck.Checked=false;return;}fishEnabled=fishCheck.Checked;cfg.FishName=Convert.ToString(fishCombo.SelectedItem)??"";Save();if(!fishEnabled&&ownsFishing){await StopFishOnly();nextPoll=DateTime.MinValue;}};p.Controls.Add(fishCheck);fishCombo.SelectedIndexChanged+=(s,e)=>{if(auto||busy){return;}cfg.FishName=Convert.ToString(fishCombo.SelectedItem)??"";Save();};p.Controls.Add(Label("ON을 켜고 상단 ‘자동화 시작’을 눌러야 실행됩니다.",10));p.Controls.Add(Label("게임에서 조회되는 물고기만 표시합니다. 낚시터는 게임이 자동 선택하며 직접 지정할 수 없습니다.",10));p.Controls.Add(Label("작업이 생기거나 가방 한도에 도달하면 이 프로그램이 시작한 낚시를 중지합니다.",10));p.Controls.Add(Label("낚시 시작은 정령의 날개 5개를 사용합니다. OFF 시 현재 낚시는 중단하지만 게임의 자동 낚시 설정 자체는 남을 수 있습니다.",10));Page("낚시","선택한 항목이 낚시를 시작하지 않으면 자동화를 중지하고 알립니다.",p,null);}
    void BuildLandmarks(){landmarkGrid=Grid("장소 이름","종류","지역","X","Y");var bar=Bar();var arrivalCheck=new CheckBox{Text="이동 완료 시 알림",Checked=cfg.ArrivalNotifications,AutoSize=true,Margin=new Padding(8,10,8,6)};arrivalCheck.CheckedChanged+=(s,e)=>{cfg.ArrivalNotifications=arrivalCheck.Checked;Save();};var dungeonCheck=new CheckBox{Text="던전 완료 시 알림",Checked=cfg.DungeonNotifications,AutoSize=true,Margin=new Padding(8,10,8,6)};dungeonCheck.CheckedChanged+=(s,e)=>{cfg.DungeonNotifications=dungeonCheck.Checked;Save();};bar.Controls.Add(arrivalCheck);bar.Controls.Add(dungeonCheck);var huntingCheck=new CheckBox{Text="사냥터 완료 시 알림",Checked=cfg.HuntingNotifications,AutoSize=true,Margin=new Padding(8,10,8,6)};huntingCheck.CheckedChanged+=(s,e)=>{cfg.HuntingNotifications=huntingCheck.Checked;Save();nextPoll=DateTime.MinValue;};bar.Controls.Add(huntingCheck);var testNotice=Button("알림 테스트",()=>Notify("알림 테스트","소리·Windows 알림·앱의 최근 알림 표시를 확인하세요."));bar.Controls.Add(testNotice);bar.SetFlowBreak(testNotice,true);activityDiagnosticButton=Button("활동 기록 시작",ToggleActivityDiagnostic);bar.Controls.Add(activityDiagnosticButton);bar.Controls.Add(Button("기록 폴더 열기",()=>{Directory.CreateDirectory(Storage.Root);ProcessFolder(Storage.Root);}));bar.SetFlowBreak(bar.Controls[bar.Controls.Count-1],true);bar.Controls.Add(Button("현재 위치 저장",SaveLandmark));bar.Controls.Add(Button("선택 장소를 도착 목표로",()=>{var l=Selected<Landmark>(landmarkGrid);if(l!=null){watched=l.Name;Log("도착 알림 시작: "+l.Name);}}));bar.Controls.Add(Button("도착 목표 해제",()=>{watched="";Log("도착 목표 해제");}));bar.Controls.Add(Button("선택 삭제",()=>{var l=Selected<Landmark>(landmarkGrid);if(l!=null){cfg.Landmarks.Remove(l);Save();RenderLandmarks();}}));activityWatchLabel=Label("활동 상태 조회 대기",9);activityWatchLabel.MaximumSize=new Size(1000,0);bar.SetFlowBreak(bar.Controls[bar.Controls.Count-1],true);bar.Controls.Add(activityWatchLabel);bar.SetFlowBreak(activityWatchLabel,true);lastNotificationLabel=Label("최근 알림: 없음",9);lastNotificationLabel.MaximumSize=new Size(1000,0);bar.Controls.Add(lastNotificationLabel);Page("이동 · 던전","현재 위치를 저장하고 도착 목표를 선택하세요. 이동은 직접 진행합니다. 도착·던전 클리어·사냥터 임무 완료를 각각 알립니다. 사냥터는 임무의 ‘완료됨’ 단계에서 알리며, 단순 중단·퇴장은 완료로 판단하지 않습니다. 이동·입장·보상 수령은 직접 진행합니다.",landmarkGrid,bar);}
    void BuildSettings(){var layout=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,240));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));var opts=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,FlowDirection=FlowDirection.TopDown,WrapContents=false};var row=Bar();row.Dock=DockStyle.None;row.Controls.Add(Label("가방 중지 기준 (%)",10));fullNumber=Number(cfg.FullPercent,100);fullNumber.Minimum=50;row.Controls.Add(fullNumber);opts.Controls.Add(row);AddDisplayScale(opts);storageCheck=new CheckBox{Text="목표 수량 계산에 계정·캐릭터 창고 포함",Checked=cfg.CountStorage,AutoSize=true,Margin=new Padding(8)};opts.Controls.Add(storageCheck);var buttons=Bar();buttons.Dock=DockStyle.None;buttons.Controls.Add(Button("설정 적용",()=>{if(!CanEdit())return;cfg.FullPercent=(int)fullNumber.Value;cfg.CountStorage=storageCheck.Checked;Save();RenderGoals();Log("설정 저장");}));buttons.Controls.Add(Button("시설별 슬롯 설정",()=>EditFacilitySlots(null)));buttons.Controls.Add(Button("게임 CLI 선택",ChooseCli));buttons.Controls.Add(Button("설정 폴더 열기",()=>{Directory.CreateDirectory(Storage.Root);ProcessFolder(Storage.Root);}));opts.Controls.Add(buttons);cliLabel=new Label{Text="CLI: "+cfg.CliPath,AutoSize=true,Margin=new Padding(8)};opts.Controls.Add(cliLabel);layout.Controls.Add(opts,0,0);logBox=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,BackColor=Color.FromArgb(28,43,46),ForeColor=Color.FromArgb(219,235,230),Font=new Font("맑은 고딕",9)};layout.Controls.Add(logBox,0,1);Page("설정 · 기록","자동화는 설정한 목표에 따라 계속 진행합니다. 가방 한도·재료 부족·게임 오류 등으로 대기하거나 중지할 수 있습니다. 정령의 날개 보유량은 상단에서 확인하세요.",layout,null);}
    void ProcessFolder(string path){System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(path){UseShellExecute=true});}
    void ChooseCli(){if(!CanEdit())return;using(var d=new OpenFileDialog{Filter="게임 CLI|MabinogiMobile_CLI.exe|실행 파일|*.exe",FileName="MabinogiMobile_CLI.exe"}){if(d.ShowDialog(this)!=DialogResult.OK)return;cfg.CliPath=d.FileName;if(!demo)bridge=new GameBridge(cfg.CliPath);hasCatalog=false;connected=false;connectionIssue="연결 확인 중";cliLabel.Text="CLI: "+cfg.CliPath;Save();nextPoll=DateTime.MinValue;}}
    T Selected<T>(DataGridView grid) where T:class {return grid.SelectedRows.Count==0?null:grid.SelectedRows[0].Tag as T;}
    bool CanEdit(){if(auto||busy||MusicActive){Notice("주크박스·자동화 또는 진행 중인 작업을 멈춘 뒤 변경하세요.","설정 변경");return false;}return true;}
    string UserError(Exception ex){Log("오류 상세: "+ex.Message);return FriendlyText.Error(ex);}
    void Notice(string message,string title="안내"){planLabel.Text=title+" · "+message;planLabel.ForeColor=Color.Firebrick;Log(title+" · "+message);}
    void Save(){if(demo||preview)return;try{Storage.Save(cfg);}catch(Exception ex){Log("설정 저장 실패: "+ex.Message);}}
    void Log(string text){string line=DateTime.Now.ToString("HH:mm:ss")+"  "+text; if(logBox!=null){logBox.AppendText(line+Environment.NewLine);if(logBox.TextLength>80000)logBox.Text=logBox.Text.Substring(logBox.TextLength-50000);}if(!demo)try{Directory.CreateDirectory(Storage.Root);File.AppendAllText(Path.Combine(Storage.Root,"events-"+DateTime.Now.ToString("yyyyMMdd")+".log"),line+Environment.NewLine);}catch{}}
    void Notify(string title,string text){Log(title+" · "+text);if(lastNotificationLabel!=null)lastNotificationLabel.Text="최근 알림 ("+DateTime.Now.ToString("HH:mm:ss")+"): "+title+" · "+text;if(!preview){try{System.Media.SystemSounds.Asterisk.Play();tray.ShowBalloonTip(7000,title,text,ToolTipIcon.Info);}catch(Exception ex){Log("Windows 알림 표시 실패: "+ex.Message);}}}
}
}
